# Generated by Django 5.1.5 on 2025-08-25 12:56

import django.db.models.deletion
import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    django_fsm.FSMField(
                        choices=[
                            ("Open", "open"),
                            ("Full", "full"),
                            ("Complete", "complete"),
                        ],
                        default="Open",
                        max_length=50,
                        protected=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("capacity", models.IntegerField(default=3)),
                (
                    "faculty",
                    models.CharField(
                        choices=[
                            ("SAAT", "SAAT"),
                            ("SBMS", "SBMS"),
                            ("SEMS", "SEMS"),
                            ("SESE", "SESE"),
                            ("SET", "SET"),
                            ("SIMME", "SIMME"),
                            ("SLIT", "SLIT"),
                            ("SLS", "SLS"),
                            ("SOC", "SOC"),
                            ("SPS", "SPS"),
                        ],
                        default="SAAT",
                        max_length=10,
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="core.trip",
                    ),
                ),
            ],
        ),
    ]
